variableNamePatterns:
  - (?i)passwd|password
  - (?i)secret
  - (?i)token
  - (?i)apiKey|api[_-]key
  - (?i)accessKey|access[_-]key
  - (?i)bearer
  - (?i)credentials
  - salt|SALT|Salt
  - (?i)signature
variableNameExclusionPattern: (?i)format|tokenizer|secretName|Error$|passwordPolicy|tokens$|tokenPolicy|[,\s#+*^|}{'"\[\]]|regex
xmlAttributeNameExclusionPattern: (?i)token #values that tend to have a different meaning for xml
valueMatchPatterns:
  - name: Postgres URI
    pattern: postgres(?:ql)?:\/\/.+:.+@.+:.+\/.+

  - name: URL With Basic Auth
    pattern: (ftp|sftp|http|https):\/\/[a-zA-Z0-9%-]+:[a-zA-Z0-9%-]+@([a-z0-9-]{0,61}\.[a-z]{2,})

  - name: JWT Token
    pattern: eyJhbGciOiJIUzI1NiIsInR5cCI[a-zA-Z0-9_.]+

  - name: Bcrypt Hash
    pattern: ^\$2[ayb]\$.{56,57}$ #57 in case it's in a string and the $ is escaped

  - name: AWS Client ID
    pattern: (A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}

  - name: SendGrid API Key
    pattern: SG\.[\w_-]{16,32}\.[\w_-]{16,64}

  - name: Amazon MMS Key
    pattern: amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}

  - name: Facebook Secret
    pattern: (?i)(facebook|fb)(.{0,20})?(?-i)['\"][0-9a-f]{32}['\"]

  - name: Facebook Access Token
    pattern: EAA[\w0-9]{9}BA[0-9A-Za-z]+

  - name: Facebook Client ID
    pattern: (?i)(facebook|fb)(.{0,20})?['\"][0-9]{13,17}['\"]

  - name: Twitter Secret
    pattern: (?i)twitter(.{0,20})?['\"][0-9a-z]{35,44}['\"]

  - name: Twitter Client ID
    pattern: (?i)twitter(.{0,20})?['\"][0-9a-z]{18,25}['\"]

  - name: Github Secret
    pattern: (?i)github(.{0,20})?(?-i)['\"][0-9a-zA-Z]{35,40}['\"]

  - name: LinkedIn Client ID
    pattern: (?i)linkedin(.{0,20})?(?-i)['\"][0-9a-z]{12}['\"]

  - name: LinkedIn Secret
    pattern: (?i)linkedin(.{0,20})?['\"][0-9a-z]{16}['\"]

  - name: Slack Token
    pattern: xox[baprs]-([0-9a-zA-Z]{10,48})?

  - name: Slack WebHook
    pattern: https:\/\/hooks\.slack\.com\/services\/T[a-zA-Z0-9_]{8}\/B[a-zA-Z0-9_]{8,10}\/[a-zA-Z0-9_]{24}

  - name: Private Key
    pattern: -----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----

  - name: Google API Key
    pattern: AIza[0-9A-Za-z\\-_]{35}

  - name: Heroku Key
    pattern: (?i)heroku(.{0,20})?['"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}['"]

  - name: MailChimp Key
    pattern: (?i)(mailchimp|mc)(.{0,20})?['"][0-9a-f]{32}-us[0-9]{1,2}['"]

  - name: MailGun Key
    pattern: (?i)(mailgun|mg)(.{0,20})?['"][0-9a-z]{32}['"]

  - name: Twilio Key
    pattern: (?i)twilio(.{0,20})?['\"][0-9a-f]{32}['\"]
fullTextValueExcludePatterns:
  - postgres(?:ql)?:\/\/.+:.+@localhost:.+\/.+ #default postgres uri for testing
  - postgres(?:ql)?:\/\/.+:.+@127.0.0.1:.+\/.+ #default postgres uri for testing
  - postgres(?:ql)?:\/\/postgres:postgres@postgres:.+\/.+ #default postgres uri for testing
variableValueExcludePatterns:
  - (?i)^test$|password|^postgres$|^root$|^foobar$|^example$|^changeme$|^default$|^master$ #common dummy values
  - (?i)^string$|^integer$|^number$|^boolean$|^xsd:.+|^literal$
  - (?i)^true$|^false$
  - (?i)^bearer$|^Authorization$
  - bootstrapper
  - \${.+\} #typically for values injected at build time
  - (?i){{.*}}
minPasswordLength: 6 #don't consider anything shorter than this as a possible credential
excludeTests: true
testDirectories:
  - test
  - tests
  - testdata
  - example
ignoreFiles: #files or directories to skip
  - vendor
  - .git
  - .idea
excludeComments: false
scanTypes: #possible values are go|yaml|json|properties|privatekey|xml|php
  - go
  - yaml
  - json
  - properties
  - privatekey
  - xml
  - php
  - bash
  - generic
  - generic_code
genericFileExtensions:
  # text files
  - txt
  - data
  - dat
  - md

  #config files
  - local
  - conf
  - config
  - dist

  #code
  - py
  - js
  - ts
  - coffee
  - html
  - xhtml
  - rb
  - kt
  - bat
  - groovy
  - gradle
  - tf
  - sql
  - sqlite
  - twig

  #other
  - csv
  - temp
  - dump
  - swagger
  - out
  - log
genericCodeFileExtensions:
  - java
  - swift
  - cpp
  - c
  - h
  - hpp
  - cs
disableOutputColors: false
verbose: false
